#!/usr/bin/env sh

VERSION=$SOURCE_BRANCH
if [ "$VERSION" == "master" ]; then
	VERSION=""
fi

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg "SOURCE_COMMIT=$GIT_SHA1" --build-arg "DOCKERFILE_PATH=$DOCKERFILE_PATH" --build-arg "SOURCE_TYPE=$SOURCE_TYPE" --build-arg "VERSION=$VERSION" -t $IMAGE_NAME .
