#!/usr/bin/env bash -e

if [[ -z "$1" ]]; then
	echo "Version required" >&2
	exit 0
fi

export VERSION="$1"
./hooks/build
./hooks/test

if [ -n "$(git status --porcelain=v1)" ]; then
  git status
  exit 1
fi

git tag "${VERSION}"
git push --tags
# update master
git push

